//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PenSamples.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Secret
    {
        public int SecretId { get; set; }
        public string Description { get; set; }
        public string Text { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
