//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PenSamples.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Secrets = new HashSet<Secret>();
        }
    
        public int UserId { get; set; }
        public string Name { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<Secret> Secrets { get; set; }
    }
}
